### ISSUE TITLE
Adding multiple fooditem_ids to an order

### ISSUE THREAD

**Issue by stevecreswick** [stevecreswick/RESTaurantApp#1]
Trying to Add Multiple Food Items

On the New Order Page (and eventually the Edit Order Page), I currently have check boxes that pass the fooditem_id value to the newly created (or edited) order.  When I select more than one item the values add together and are stored as a single integer.  Because of this, I can only show one food item on the order show page.  I think this is because the type for the fooditem_id column is Integer.  If I change it to a string would that then allow me to have multiple fooditem_id's for an order?  Or is there another way for me to store multiple fooditem_ids and display them.

**Comment by amadden80** [comment]
_In Person_
