### ISSUE TITLE
Using Active Support

### ISSUE THREAD

**Issue by stevecreswick** [stevecreswick/RESTaurantApp#4]
I would like to use active support for its useful number_to_currency and similar methods.  I see that it is a gem required by Active Record and so it is on my machine, but I cannot figure out where to require it and how to use it.

**Comment by emilylordahl** [comment]
We instructors will be in a meeting from 12:30–1:45. I've not used ActiveSupport but when we get back we can try to take a look if you haven't figured it out by then.

**Comment by emilylordahl** [comment]
You could also try using `sprintf` with Ruby.

http://ruby-doc.org/core-2.2.0/Kernel.html#method-i-sprintf

If used correctly, this will display your prices as $5.00 (but remember, it's still a string so you'll need to convert it to a float using `to_f` to perform arithmetic with it).

**Comment by rapala61** [comment]
I managed to use it by adding the active support gem to my project:
`gem 'activesupport`` 
 then using it this way in my controller
`ActiveSupport::NumberHelper.number_to_currency(56.5)   # $56.50`

Im not sure this is the best way to include it, but its one.

**Comment by emilylordahl** [comment]
Cool! I was going to say, you should just need to add it to your Gemfile to
be able to use it. Whatever works! We can always refactor later if we learn
a better way to use it.

On Thu, Aug 27, 2015 at 2:20 PM, Rafael notifications@github.com wrote:

> I managed to use it by requiring adding the active support gem to my
> project:
> gem 'activesupport`
> then requiring then using it this way in my controller
> ActiveSupport::NumberHelper.number_to_currency(56.5) # $56.50
> 
> Im not sure this is the best way to include it, but its one.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/stevecreswick/RESTaurantApp/issues/4#issuecomment-135513119
> .

## 

_Emily Lordahl *| *Instructional Associate_ | _WDI_
General Assembly | 10 E 21st St, 2nd Floor | New York, NY 10010
emily.lordahl@generalassemb.ly
https://generalassemb.ly/

**Comment by emilylordahl** [comment]
Thanks Rafa.

On Thu, Aug 27, 2015 at 2:31 PM, Emily Lordahl <
emily.lordahl@generalassemb.ly> wrote:

> Cool! I was going to say, you should just need to add it to your Gemfile
> to be able to use it. Whatever works! We can always refactor later if we
> learn a better way to use it.
> 
> On Thu, Aug 27, 2015 at 2:20 PM, Rafael notifications@github.com wrote:
> 
> > I managed to use it by requiring adding the active support gem to my
> > project:
> > gem 'activesupport`
> > then requiring then using it this way in my controller
> > ActiveSupport::NumberHelper.number_to_currency(56.5) # $56.50
> > 
> > Im not sure this is the best way to include it, but its one.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/stevecreswick/RESTaurantApp/issues/4#issuecomment-135513119
> > .
> 
> ## 
> 
> _Emily Lordahl *| *Instructional Associate_ | _WDI_
> General Assembly | 10 E 21st St, 2nd Floor | New York, NY 10010
> emily.lordahl@generalassemb.ly
> https://generalassemb.ly/

## 

_Emily Lordahl *| *Instructional Associate_ | _WDI_
General Assembly | 10 E 21st St, 2nd Floor | New York, NY 10010
emily.lordahl@generalassemb.ly
https://generalassemb.ly/

**Comment by stevecreswick** [comment]
Cool, that worked.  This was the part I was missing (
ActiveSupport::NumberHelper.
).

Thank you both!
ᐧ

**Comment by emilylordahl** [comment]
:+1::+1::+1::+1:
